### ISSUE TITLE
"Minimize to Tray" not working

### ISSUE THREAD

**Issue by Coldblackice** [Valentin-Metz/TwitchDropsMiner#51] opened 2024-04-27 06:35 UTC
Great fork! Thanks for your work on this, particularly being able to do unlinked items. 

Minor issue: "_Minimize to Tray_" function doesn't work. Likewise, when starting the miner with a _minimize-to-tray_ switch, the tray icon never appears, instead running without any interface in the background. The only way to exit it is a force-close/taskkill.

Currently on latest commit 83104d1, built 3/8/2024.

**Comment by Valentin-Metz** [comment] 2024-05-05 23:52
@jaredkotoff has done improvements to the GUI before; I'm mainly running this on a server.
Maybe he has some ideas on what we'd need to change for this to work.
(The program just running in the background is our default intended behavior, but I see why one might still wish to have it in tray if you are using it via GUI)

**Comment by jaredcat** [comment] 2024-05-06 00:06
First thing, does that feature work on the original project?  
Just to make sure that it's actually problem introduced in changes to this fork.

**Comment by Coldblackice** [comment] 2024-05-14 18:05
@jaredkotoff Yes, minimize-to-tray does work properly in DevilXD's repo (at least last time I tried it). I can test/troubleshoot further if you have any suggestions.

**Comment by jaredcat** [comment] 2024-05-21 19:24
@Coldblackice this doesn't work because `pystray` was removed from this fork
https://github.com/Valentin-Metz/TwitchDropsMiner/commit/770267140e927c64c2251fab1774a6010e856381 

If you know how to code, you can probably try adding it back while making sure it doesn't break any of the headless/docker stuff and see what @Valentin-Metz says

**Comment by Valentin-Metz** [comment] 2024-05-22 09:25
Ah, yes, I remember it making problems.
@Coldblackice if you want to add it back in, feel free to do so, but please make sure it works in the Docker container if you do.

**Comment by Coldblackice** [comment] 2024-05-25 02:05
@jaredkotoff @Valentin-Metz Thanks for the info, good to know and will do.

By chance, do you remember what problems it was causing (or at least what type)?

**Comment by Valentin-Metz** [comment] 2024-05-25 03:35
> By chance, do you remember what problems it was causing (or at least what type)?

It was causing issues with the program starting in Docker.
Either because it was outdated at the time, or because it can't handle a tray "not existing".
There is probably a way to integrate it without making the entire program crash when its running in a no display environment, it simply hasn't been done yet.

**Comment by Valentin-Metz** [comment] 2024-06-07 19:04
Fixed with bab6b256d9e843546faf5da9d811b01527bc1ca2.

**Closed as completed by Valentin-Metz** 2024-06-07 19:04 UTC
